import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { TelegramSDKInitProvider } from "@src/context/telegramContext/TelegramSdkInitProvider"
import AppInitProvider from "@src/context/AppInitProvider"
import TqClientProvider from "@src/context/TqClientProvider"

import "./globals.css"
import { cn } from "@src/lib/utils"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="flex justify-center">
      <body
        className={cn(
          "bg-background text-text-color max-w-max-size flex h-[100dvh] w-full items-start justify-center",
          `${geistSans.variable} ${geistMono.variable}`
        )}
      >
        <TelegramSDKInitProvider>
          <AppInitProvider>
            <TqClientProvider>{children}</TqClientProvider>
          </AppInitProvider>
        </TelegramSDKInitProvider>
      </body>
    </html>
  )
}
